export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {

    home: '/dashboard/home',

    part1: '/dashboard/part1/sub1',
    part1_sub1: '/dashboard/part1/sub1',
    part1_sub2: '/dashboard/part1/sub2',
    part1_sub3: '/dashboard/part1/sub3',
    part1_sub4: '/dashboard/part1/sub4',
    part1_sub5: '/dashboard/part1/sub5',
    part1_sub6: '/dashboard/part1/sub6',
    part1_sub7: '/dashboard/part1/sub7',
    part1_sub8: '/dashboard/part1/sub8',
    part1_sub9: '/dashboard/part1/sub9',

    part2: '/dashboard/part2/sub1',
    part2_sub1: '/dashboard/part2/sub1',
    part2_sub2: '/dashboard/part2/sub2',
    part2_sub3: '/dashboard/part2/sub3',
    part2_sub4: '/dashboard/part2/sub4',
    part2_sub5: '/dashboard/part2/sub5',
    part2_sub6: '/dashboard/part2/sub6',
    part2_sub7: '/dashboard/part2/sub7',
    part2_sub8: '/dashboard/part2/sub8',
    part2_sub9: '/dashboard/part2/sub9',
    part2_sub10: '/dashboard/part2/sub10',
    part2_sub11: '/dashboard/part2/sub11',
    part2_sub12: '/dashboard/part2/sub12',
    part2_sub13: '/dashboard/part2/sub13',
    part2_sub14: '/dashboard/part2/sub14',
    part2_sub15: '/dashboard/part2/sub15',
    part2_sub16: '/dashboard/part2/sub16',
    part2_sub17: '/dashboard/part2/sub17',

    part3: '/dashboard/part3/sub1',
    part3_sub1: '/dashboard/part3/sub1',
    part3_sub2: '/dashboard/part3/sub2',
    part3_sub3: '/dashboard/part3/sub3',
    part3_sub4: '/dashboard/part3/sub4',
    part3_sub5: '/dashboard/part3/sub5',
    part3_sub6: '/dashboard/part3/sub6',
    part3_sub7: '/dashboard/part3/sub7',
    part3_sub8: '/dashboard/part3/sub8',
    part3_sub9: '/dashboard/part3/sub9',


    //0609前
    // part1: '/dashboard/part1/sub1',
    // part1_sub1: '/dashboard/part1/sub1',
    // part1_sub2: '/dashboard/part1/sub2',
    // part1_sub3: '/dashboard/part1/sub3',
    // part1_sub4: '/dashboard/part1/sub4',
    // part1_sub5: '/dashboard/part1/sub5',
    // part1_sub6: '/dashboard/part1/sub6',
    // part1_sub7: '/dashboard/part1/sub7',
    // part1_sub8: '/dashboard/part1/sub8',
    // part1_sub9: '/dashboard/part1/sub9',
    // part1_sub10: '/dashboard/part1/sub10',
    // part1_sub11: '/dashboard/part1/sub11',
    // part1_sub12: '/dashboard/part1/sub12',
    // part1_sub13: '/dashboard/part1/sub13',
    // part1_sub14: '/dashboard/part1/sub14',
    // part1_sub15: '/dashboard/part1/sub15',

    // part2: '/dashboard/part2/sub1',
    // part2_sub1: '/dashboard/part2/sub1',
    // part2_sub2: '/dashboard/part2/sub2',
    // part2_sub3: '/dashboard/part2/sub3',

    // part3: '/dashboard/part3/sub1',
    // part3_sub1: '/dashboard/part3/sub1',
    // part3_sub2: '/dashboard/part3/sub2',
    // part3_sub3: '/dashboard/part3/sub3',
    // part3_sub4: '/dashboard/part3/sub4',
    // part3_sub5: '/dashboard/part3/sub5',
    
    
    // part4: '/dashboard/part4/sub1',
    // part4_sub1: '/dashboard/part4/sub1',
    // part4_sub2: '/dashboard/part4/sub2',
    // part4_sub3: '/dashboard/part4/sub3',
    // part4_sub4: '/dashboard/part4/sub4',
    // part4_sub5: '/dashboard/part4/sub5',
    // part4_sub6: '/dashboard/part4/sub6',
    // part4_sub7: '/dashboard/part4/sub7',
    // part4_sub8: '/dashboard/part4/sub8',

    // part5: '/dashboard/part5/sub1',
    // part5_sub1: '/dashboard/part5/sub1',
    // part5_sub2: '/dashboard/part5/sub2',
    // part5_sub3: '/dashboard/part5/sub3',

  },
  errors: { notFound: '/errors/not-found' },
} as const;
