export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    part1: '/dashboard/part1/sub1',
    part1_sub1: '/dashboard/part1/sub1',
    part1_sub2: '/dashboard/part1/sub2',
    part1_sub3: '/dashboard/part1/sub3',
    part1_sub4: '/dashboard/part1/sub4',
    part1_sub5: '/dashboard/part1/sub5',
    part1_sub6: '/dashboard/part1/sub6',
    part1_sub7: '/dashboard/part1/sub7',
    part1_sub8: '/dashboard/part1/sub8',
    part1_sub9: '/dashboard/part1/sub9',
    part1_sub10: '/dashboard/part1/sub10',
    part1_sub11: '/dashboard/part1/sub11',
    part1_sub12: '/dashboard/part1/sub12',
    part1_sub13: '/dashboard/part1/sub13',
    part1_sub14: '/dashboard/part1/sub14',
    part1_sub15: '/dashboard/part1/sub15',

    
    // part1: '/dashboard/part1/sub1',
    // part1_sub1: '/dashboard/part1/sub1',
    // part1_sub2: '/dashboard/part1/sub2',
    // part2: '/dashboard/part2/sub1',
    // part2_sub1: '/dashboard/part2/sub1',
    // part2_sub2: '/dashboard/part2/sub2',
    // part3: '/dashboard/part3/sub1',
    // part3_sub1: '/dashboard/part3/sub1',
    // part3_sub2: '/dashboard/part3/sub2',
    // part3_sub3: '/dashboard/part3/sub3',
    // part4: '/dashboard/part4/sub1',
    // part4_sub1: '/dashboard/part4/sub1',
    // part5: '/dashboard/part5/sub1',
    // part5_sub1: '/dashboard/part5/sub1',
    // part5_sub2: '/dashboard/part5/sub2',
    // part5_sub3: '/dashboard/part5/sub3',

  },
  errors: { notFound: '/errors/not-found' },
} as const;
